name: the_learning_nest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  lottie: ^3.3.1
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.14.0
  flutter_dotenv: ^5.2.1
  fl_chart: ^0.64.0
  file_selector: ^1.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
