name: the_learning_nest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  lottie: ^3.3.1
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.14.0
  flutter_dotenv: ^5.2.1
  fl_chart: ^0.64.0
  file_selector: ^1.0.3
  firebase_storage: ^11.6.5
  uuid: ^4.3.3
  url_launcher: ^6.1.7
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  video_player: ^2.7.2
  chewie: ^1.7.4
  flutter_pdfview: ^1.2.7
  open_filex: ^4.3.2
  path_provider: ^2.1.2
  http: ^1.4.0
  flutter_rating_bar: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lottie/upload.jpg
